q1_joint :   # MX-64
   return_delay_time     : 0    # item name : value
   operating_mode        : 3    # 0: current; 1: velocity; 3: position; 5: current base position; 20: pwm
   shutdown              : 20
   homing_offset         : 0
   max_position_limit    : 2700   #  57.3 deg
   min_position_limit    : 1396   # -57.3 deg
   velocity_limit        : 150
   goal_position         : 2048   # 0-4095
   goal_current          : 1941   # 0-1941
   goal_velocity         : 50    # 0-1023
   position_p_gain       : 850    # 0-16383
   position_i_gain       : 0      # 0-16383
   position_d_gain       : 0      # 0-16383
   velocity_p_gain       : 50
   velocity_i_gain       : 0
   profile_velocity      : 40
   profile_acceleration  : 0