wheel1: # XM-430-W350
  return_delay_time: 0 # item name : value
  operating_mode: 1 #  current: 0 ; velocity: 1; position: 3; extended_position: 4; current base position: 4; pwm: 20
  shutdown: 20
  homing_offset: 0
  max_position_limit: 4000 #  57.3 deg
  min_position_limit: 1 # -57.3 deg
  velocity_limit: 1023
  goal_position: 2048 # 0-4095
  goal_current: 1941 # 0-1941
  goal_velocity: 0 # 0-1023
  position_p_gain: 850 # 0-16383
  position_i_gain: 0 # 0-16383
  position_d_gain: 0 # 0-16383
  velocity_p_gain: 100
  velocity_i_gain: 1920
  profile_velocity: 100 #!!
  profile_acceleration: 0
wheel2: # XM-430-W350
  return_delay_time: 0 # item name : value
  operating_mode: 3 #  current: 0 ; velocity: 1; position: 3; extended_position: 4; current base position: 4; pwm: 20
  shutdown: 20
  homing_offset: 0
  max_position_limit: 4000
  min_position_limit: 1
  velocity_limit: 1023 #!!
  goal_position: 2048 # 0-4095
  goal_current: 1941 # 0-1941
  goal_velocity: 0 # 0-1023 !!
  position_p_gain: 850 # 0-16383
  position_i_gain: 0 # 0-16383
  position_d_gain: 0 # 0-16383
  velocity_p_gain: 100
  velocity_i_gain: 1920
  profile_velocity: 100 #!!
  profile_acceleration: 0